"""empty message

Revision ID: 55731fc4e37c
Revises: 9bbf426a52fd
Create Date: 2022-08-11 23:37:29.594792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55731fc4e37c'
down_revision = '9bbf426a52fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
