"""empty message

Revision ID: ef0449079f8c
Revises: e10bd3edf94d
Create Date: 2022-08-22 15:56:09.288062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0449079f8c'
down_revision = 'e10bd3edf94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genre', sa.String(length=120), nullable=False))
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artists', 'genre')
    # ### end Alembic commands ###
